door_approach_goal_generator_node:
  plane_topic: /door/plane_map
  handle_topic: /door/handle_pose_map
  goal_topic: /tiago_move_base_control/goal
  trigger_topic: /tiago_move_base_control/generate_goal

  stand_off_m: 0.75
  lateral_offset_m: 0.00

  use_handle_as_target: true
  face_door: true
  normal_sign: -1

  continuous: false
  min_update_period_s: 0.5