move_group_name: "arm_right"
ee_link: "arm_right_7_link"
gripper_controller: "hand_right_controller"
gripper_joint_names:
  - "hand_right_thumb_joint"
  - "hand_right_index_joint"
  - "hand_right_mrl_joint"

move_group_name_left: "arm_left"
ee_link_left: "arm_left_7_link"
gripper_controller_left: "hand_left_controller"
gripper_joint_names_left:
  - "hand_left_thumb_joint"
  - "hand_left_index_joint"
  - "hand_left_mrl_joint"

hinge_side_topic: "/door/hinge_side"

planning_frame: ""
base_frame_fallback: "base_footprint"
handle_topic: "/door/handle_pose_map"

position_tolerance: 0.01
orientation_tolerance: 0.05
velocity_scaling: 0.2
acceleration_scaling: 0.2

approach_distance: 0.12
lateral_offset: 0.00
vertical_offset: 0.00

named_home: ""
named_stow: ""